### ISSUE TITLE
analytics chart 

### ISSUE THREAD

**Issue by scheung38** [colinrcummings/daily_ui#1]
Hi Colin,

Tried to run your 018_analytics_chart in my own project and just opening the 018_analytics_chart.html locally, within inspector I get

Running these are fine:

http://colinrcummings.github.io/daily_ui/018_analytics_chart
http://localhost:63343/daily_ui/018_analytics_chart.html?_ijt=i0avg4psklsojjvpg49snt64is

But my version:

http://localhost:63343/stormpath-express-react-example/018_analytics_chart.html?_ijt=ukrb97gpctoo8mnrjnlm3jh1gd

browser.js:3 Uncaught ReferenceError: exports is not defined
node_modules/babel-core/lib/api/browser.js: 3

where i started using stormpath-express-react-example as a starting point.

But basically it seems the fa fa arrow down disappears.

Tried babel-loader as suggested

http://stackoverflow.com/questions/29434978/babel-generated-code-causes-error-exports-is-undefined

and webpack-config.js

```
/* eslint-disable no-var */
var path = require('path');
var webpack = require('webpack');

module.exports = {
  entry: [
    './src/js/app'
  ],
  devtool: 'eval-source-map',
  output: {
    path: __dirname,
    filename: 'app.js',
    publicPath: '/js/'
  },
  module: {
    loaders: [{
      test: /\.js$/,
      loaders: ['babel', 'babel-loader'], //'babel'
      include: path.join(__dirname, 'src/js')
    }]
  }
};
```

But still not working

![screen shot 2016-09-17 at 15 19 58](https://cloud.githubusercontent.com/assets/1273014/18608772/4429ba38-7cea-11e6-8b91-8eacf54bbfbe.png)

This is my sample data format, do I need to reformat it before rendering in D3?

```
Channel_Name,  Date_Time+Time, Offset, Value, Code

9334638004/01,01/08/2015 01:30,1,11.223,0
9334638004/01,01/08/2015 02:00,1,0,0
9334638004/01,01/08/2015 02:30,1,22.445,0
```

**Comment by colinrobertbrooks** [comment]
Sebastian,

My directory uses UMD; you're using CommonJS and `require` statements aren't being transpiled properly (i.e. browsers don't support CommonJS 'require', 'export`, etc). The icon is from [FontAwesome](http://fontawesome.io/) and isn't tied to [D3](https://d3js.org/)/[NVD3](http://nvd3-community.github.io/nvd3/examples/documentation.html), which render the chart. You need to revise your build process.
